server:
  port: 8084
spring:
  application:
     name: car-lease
eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8085/eureka
cars:
  client:
    baseUrl: api/v1/car/
    endpoint: /carId
    hostname: CAR-SERVICE
    timeout:
      connectSeconds: 5
      readSeconds: 20