server:
  port: 8084
spring:
  application:
     name: car-lease
  h2:
    console:
      enabled: true
  datasource:
         url: jdbc:h2:mem:car-lease
         username: sa
   #      password: password
         driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

cars:
  client:
    baseUrl: api/v1/car/
    hostname: localhost
    port: 8081

customer:
  client:
    baseUrl: api/v1/customer/
    hostname: localhost
    port: 8083

restTemplate:
  timeout:
      connectSeconds: 5
      readSeconds: 20

entityManager:
  packagesToScan : com.carlease.lease